Document: qtden
Title: Debian qtden Manual
Author: <insert document author here>
Abstract: This manual describes what qtden is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtden/qtden.sgml.gz

Format: postscript
Files: /usr/share/doc/qtden/qtden.ps.gz

Format: text
Files: /usr/share/doc/qtden/qtden.text.gz

Format: HTML
Index: /usr/share/doc/qtden/html/index.html
Files: /usr/share/doc/qtden/html/*.html
